GET /microdust/time
EFUB-SeeMe/SeeMe_Server pull request #25
Opened 2021-07-18 19:53 UTC by sukyeongs

현재 시간 정보만 받아오면 구현 완료

2021-07-18 19:54 UTC, sukyeongs reviewed
현재 microdustTimeUrl에서의 현재 시간 미세먼지 값이 많이 튀어서, 주은이가 불러온 현재 미세먼지 (pm10, pm25)값을 그대로 불러와야 함.

2021-07-18 20:12 UTC, sukyeongs commented on src/main/resources/application.yml
> +microdust-time-key:
microdust-time-url과 microdust-time-key 를 추가하였습니다.

2021-07-18 20:13 UTC, sukyeongs commented on src/main/java/com/seeme/util/MicrodustUtil.java
>  	}
UTC를 KST로 변환하기 위한 getTime logic을 구현했습니다.

2021-07-18 20:13 UTC, sukyeongs commented on src/main/java/com/seeme/util/MicrodustUtil.java
> +	public static final String API_KEY = "apikey";
Api url을 위한 필드들을 추가하였습니다.

2021-07-18 20:16 UTC, sukyeongs commented on src/main/java/com/seeme/service/api/MicrodustOpenApi.java
> +			String time = MicrodustUtil.getTime(clock[0]) + "시";
현재 시간 + 예측 시간 19개 = 총 20개의 데이터를 띄우기 위해 반복문을 사용하여 api에 접근하는 것이빈다.

2021-07-18 22:29 UTC, hoit1302 commented on src/main/resources/application.yml
> +microdust-time-key:
공유문서에서 설정 파일 변경에 대해서 설명해주세요 !!

2021-07-18 22:32 UTC, hoit1302 requested changes
코드를 보면 엔터 이후 탭 키가 8칸 정도 되는데, 이걸 4칸으로 줄여서 모든 파일을 묶어 style commit message로 다시 업로드해주세요 !

2021-07-18 22:34 UTC, hoit1302 commented on src/main/java/com/seeme/controller/MicrodustController.java
> +										  @RequestParam(required = false) Double lat, @RequestParam(required = false) Double lon) {
이런 부분은 ctrl+alt+L 이후에도 기존의 방식대로 되돌려 최소한의 변경사항으로 올려주세요 ㅠㅠ

2021-07-19 10:16 UTC, sukyeongs commented on src/main/java/com/seeme/controller/MicrodustController.java
> +										  @RequestParam(required = false) Double lat, @RequestParam(required = false) Double lon) {
pr 보내고 나서 저기가 너무 지나치게 띄워져 있길래 한 tab 줄이려고 뒤로 가기를 누르면 tab이 줄어드는게 아니라 한 행 위로 올라가서 ㅠㅠ 어떻게 해야 하는지 구글링 해보고 얼른 수정해서 올릴게요

2021-07-19 10:57 UTC, hoit1302 commented on src/main/java/com/seeme/controller/MicrodustController.java
> +										  @RequestParam(required = false) Double lat, @RequestParam(required = false) Double lon) {
사실 이건 저도 첫번째 변경사항 대로 코드가 띄어지는데 그렇게 하면 첫 시작이 너무 멀어 가독성이 너무 떨어져서 임의적으로 전 줄과 탭 한번만 두게 해서 올려요!

2021-07-19 10:58 UTC, hoit1302 approved these changes
LGTM

2021-07-19 10:58 UTC, merged